### ISSUE TITLE
이슈 발행 test

### ISSUE THREAD

**Issue by JayLee-98** [reValuper/revelup#2]
##문제 제기
- 처음 사용해보는 이슈 발행 템플릿을 사용해봅니다.

##기능 요약
- 수업 자료 중 깃 허브 협업 가이드를 참고하여 이슈를 날려봅니다.

##기능 설명
- HTML, CSS, JS를 끝낸 후 마일드스톤을 설정해야합니다.

##TO-DO 리스트
- [] HTML 작성
- [] CSS 작성
- [] JS 작성
- 마일드스톤 설정

##비고
- 여기에 해당 기능에 대한 스크린샷이나 상세 설명, 레퍼런스 등을 작성해주세요. (선택)

**Comment by KIMHYEONJI13** [comment]
이슈 발행 확인

**Comment by her9797** [comment]
이슈 발행 확인

**Comment by JayLee-98** [comment]
### H를 누르시면 헤딩 처리가 됩니다.
**B를 누르시면 볼드체 처리가 됩니다.**
_I를 누르시면 이탈리안체 처리가 됩니다._
`백킷을 누르시면 코드를 입력하실 수 있습니다.`
